### ISSUE TITLE
invalid client id error

### ISSUE THREAD

**Issue by xiuliren** [hanguokai/youku#3]
Thanks for making this great package!

Not sure that whether this is my setting error or your package bug. 
I have checked and tried quite a few times of my client id, it should be correct. 

I found similar questions here, looks like a common problem.
https://zhidao.baidu.com/question/520143398.html

**Comment by hanguokai** [comment]
You need to create a app from youku(http://cloud.youku.com/app) and get it's client_id . Then use this client_id to initialize YoukuXXX class. If you still have this error, can you tell me which class and method you used?

**Comment by xiuliren** [comment]
thanks, I have an APP and it's client_id.
I simply followed your example in README. here is my code:
https://github.com/PCCES/videomover/blob/master/videomover/upload2youku.py#L8

here is the error I get:
```
Traceback (most recent call last):
  File "upload2youku.py", line 28, in <module>
    upload( args.filename, args.title )
  File "upload2youku.py", line 18, in upload
    youku.upload( file_info )
  File "/home/jingpeng/lib/anaconda3/lib/python3.6/site-packages/youku/youku_upload.py", line 322, in upload
    self.create(self.prepare_video_params(**params))
  File "/home/jingpeng/lib/anaconda3/lib/python3.6/site-packages/youku/youku_upload.py", line 126, in create
    check_error(r, 201)
  File "/home/jingpeng/lib/anaconda3/lib/python3.6/site-packages/youku/util.py", line 40, in check_error
    error['description'], response.status_code)
youku.util.YoukuError: http_status: 200, error: 1005, SystemException, Client id invalid
```
BTW, I use python3.6

**Comment by hanguokai** [comment]
hello, you should use ```access_token``` instead of ```client_secret```. They are different. ```access_token``` can be found in http://cloud.youku.com/tools in the 3rd tab.

**Comment by xiuliren** [comment]
I tried that but still have the same error..

**Comment by amrutadotorg** [comment]
I have the same error, any suggestions?

**Comment by hanguokai** [comment]
It is returned from Youku server, https://cloud.youku.com/docs?id=142 .

**Comment by amrutadotorg** [comment]
this official lib from
http://cloud.youku.com/down
works
http://ytcloud.oss-cn-shanghai.aliyuncs.com/sdk/YoukuUploadSDK_python_2017042017.zip

**Comment by hanguokai** [comment]
@amrutadotorg Thanks for reporting. This lib was released in Jan 2015, the official version also based on this lib. I will check the difference.

**Comment by hanguokai** [comment]
@amrutadotorg @jingpengw 

I updated youku python client to version 0.1.0 which use `api.youku.com` instead of `openapi.youku.com` .  

I contacted staff of youku. "openapi" is old youku api , which throw "client id invalid" error if you use new created app but "api" don't throw this error.

**Comment by amrutadotorg** [comment]
thank you, now it works :)
