### ISSUE TITLE
V2 compatibility 

### ISSUE THREAD

**Issue by amrutadotorg** [hanguokai/youku#5]
Hi. 
Youku doesn't use openapi.youku.com since 21-04-2017, they replace it with  api.youku.com . 
Can you make your code compatible with v2 version?

You can see the following code, url = 'https://api.youku.com/uploads/create.json' .
It's different with old code. url = 'https://openapi.youku.com/v2/uploads/create.json'

**Comment by hanguokai** [comment]
Thanks, I will check it.

**Comment by hanguokai** [comment]
Done. I updated api url from openapi.youku.com to api.youku.com .
You can update this lib to 0.1.0 by pip (`pip install --upgrade youku`)
