### ISSUE TITLE
http_status: 200, error: 1005, SystemException, Client id invalid when using find_videos_by_ids

### ISSUE THREAD

**Issue by amrutadotorg** [hanguokai/youku#6]
Hi, can you check the `youku.find_videos_by_ids` method? 

while using `youku.find_videos_by_ids(ids)` I'm getting 

`http_status: 200, error: 1005, SystemException, Client id invalid `

the same client ID  works fine with uploading 

my 
`ids = ['XMzg3NzcwNjEwNA==']`
thank you

**Comment by hanguokai** [comment]
I found there are only two apis on Youku docs for videos now https://cloud.youku.com/docs/doc?id=43 . Those two apis are `find_videos_by_me` and `find_video_detail_by_id` . I don't know whether other old apis supported in new api url. Can you test these by changing source code in youku_videos.py? If it works, I can update it.

**Comment by amrutadotorg** [comment]
Hi I checked but I'm getting 404 so the old link should work but it does not. Can you ask the support please? (I do not speak Chinese)

**Comment by hanguokai** [comment]
I simply test api.youku.com , it doesn't support old `find_video_by_id` method. But you can use `find_video_detail_by_id` method instead, it is ok, I updated it last time.

**Comment by amrutadotorg** [comment]
It looks like only these two methods are currently supported
http://cloud.youku.com/docs/doc?id=43

**Comment by amrutadotorg** [comment]
Thank you` find_video_detail_by_id` works fine.
